### PR TITLE
AntiCheat against cheaters that hit from a distance.

### PR DESCRIPTION
**Pull request by TheFirewall**

### CODE REVIEW

**Comment by KairusDarkSeeker** [comment]
You mean antireach?

**Comment by Creeperface01** [comment]
4 is the max distance in vannila?

**Comment by Creeperface01** [comment]
You cannot use max vannila range for max server range.. server sees distance between players differently than client.

**Comment by TheFirewall** [comment]
There are cheats that allow you to beat at a distance of 10-30 blocks, there is no other choice against this.

**Comment by Creeperface01** [comment]
Im talking about max distance

**Pull request closed without merging**
