### PR TITLE
Added Pressed Dirt

### PR DESCRIPTION
**Pull request by RandomAltThing**
(TheDiamondYT is my git account)

Added Pressed Dirt which can be made by tapping grass with wooden shovel.

### CODE REVIEW

**Comment by RandomAltThing** [comment]
Im fixing the error...

**Comment by RandomAltThing** [comment]
Hmm i cant fix the error. And its actually called tile.grassPath.name ;)

**Comment by NiclasOlofsson** [comment]
It's because now it's another problem. "tile.grassPath.name". SO you would suggest that the class should be named "TileGrassPathName" .. that would be pretty weird, don't you think?

**Comment by NiclasOlofsson** [comment]
If you fix all the other things, i can fix the compile error. Not a big problem really.

**Comment by RandomAltThing** [comment]
I am back home but on my android device. I'm going to git clone using the app SGit and I will have more time to add stuff and not rush (Because now I have all day)

**Pull request closed without merging**
