### PR TITLE
Bug with the inventory in version 0.13.0!

### PR DESCRIPTION
**Pull request by Vladik46**
More than one item in your inventory to store impossible!

### CODE REVIEW

**Comment by D3thw0lf** [comment]
Only me (Windows 10 Edition which is the same as pocket) that you can't craft anything and place, for example, grass everywhere? I hope not. :(

**Comment by kennethgomad03** [comment]
well its an item that never go out

**Comment by NiclasOlofsson** [comment]
I don't even get this one.

**Comment by kennethgomad03** [comment]
this is possibly had change the shovel instead or air as to have empty hotbars?

**Comment by NiclasOlofsson** [comment]
?

**Pull request closed without merging**
