### PR TITLE
1.0 blocks

### PR DESCRIPTION
**Pull request by TruDan**
Doing my routine Add-Blocks-To-Minet Enjoy :)

### CODE REVIEW

**Comment by NiclasOlofsson** [comment]
Thank you. Keep up that routine :-) Now we just need someone to do items too :-P

**Comment by TruDan** [comment]
Ill do the items today if I get bored ;) it looks really minecrafty when
doing it in the office. I needed the blocks done for our update so went and
did them all.

Some of the conversions were really strange though. Like purpur slabs are
red sandstone slabs with meta o.o rather than their own id like on pc (even
though the id isn't used in pe)

**Comment by NiclasOlofsson** [comment]
I wonder why it because PurPur .. and not Purpur tho ..

**Comment by TruDan** [comment]
Idk, ask my cat

**Pull request merged**
