### PR TITLE
Adding the PE server! Now available

### PR DESCRIPTION
**Pull request by tigerza117**
https://minecraftpocket-servers.com/server/63567/

### CODE REVIEW

**Comment by Ragnok123** [comment]
This server is not on MiNET

**Comment by tigerza117** [comment]
image
Server Working on MiNET 100% loooooooooooool

**Comment by Ragnok123** [comment]
So why is it on server-list? MiNET doesn't have query like PM

**Comment by tigerza117** [comment]
image
worl on server-list

**Comment by Ragnok123** [comment]
And also, if you have MiNET, you need have online 100+

**Comment by tigerza117** [comment]
Now it's late The players sleep because tomorrow they have to go to school, but I have tested. 180 players are going to be slippery and without any problems. The test is open 48 hours, then normal.

**Comment by tigerza117** [comment]
image

**Comment by Ragnok123** [comment]
Fact, that at one moment were 100+ people doesn't play. Practically today the highest numbers in hours was 30-60. Just wait, when your online per day will be example 150-200, and then try apply.

**Comment by tigerza117** [comment]
Its time to play it is 6.00 PM time zone bangkok.

**Pull request closed without merging**
