### PR TITLE
Added podzol and spawner

### PR DESCRIPTION
**Pull request by Synchunky**
See? I can be helpful

### CODE REVIEW

**Comment by NiclasOlofsson** [comment]
I don't understand. Since i don't know you from before, I don't know who told you you couldn't be helpful?

**Comment by TheDiamondYT** [comment]
I am @RandomAltThing and I am here to help. If I wasn't, I wouldn't go through the trouble to create tons of alt accounts, would I?! 

Also, check twitter as a growing hosting company wants to use your software for their servers. We are kinda partnered with leet. I sent you a tweet.

Also, I will continue to make accounts until you let me help (That could be a long time, and tell the github staff whatever you want)

**Comment by TheDiamondYT** [comment]
@NiclasOlofsson

**Comment by PEMapModder** [comment]
@TheDiamondYT I think you are causing more trouble instead of helping.

**Comment by NiclasOlofsson** [comment]
Yeah, that's just about right. There will never be a situation where I will accept an issue or code from this guy. github has received reports of these accounts as abuse and I hope they will take appropriate action. But remeber that the guy is just 12 years old, so he just ended up a bit outside of his legue with these things.

**Comment by FDKPIBC** [comment]
Do not do anything stupid.

**Pull request closed without merging**
