### PR TITLE
how to instal this in android pocketmine server?

### PR DESCRIPTION
**Pull request by MateiGamingYTB**

### CODE REVIEW

**Comment by NycuRO** [comment]
Ce penibil esti.

**Comment by NiclasOlofsson** [comment]
We all seem to agree that this PR will be merged and sent to PlayStore, right?!

**Comment by NiclasOlofsson** [comment]
Or @dktapps, could you perhaps expedite a plugin review to get MiNET working in PocketMine on PMMP?

**Comment by Creeperface01** [comment]
:D

**Pull request closed without merging**
