### PR TITLE
Update ItemFactory.cs

### PR DESCRIPTION
**Pull request by Vladik46**

### CODE REVIEW

**Comment by Pub4Game** [comment]
Ммм

**Comment by Vladik46** [comment]
Что-то нужно?

**Comment by seria2** [comment]
Таблички еще не готовы...

**Comment by NiclasOlofsson** [comment]
Sorry, have no clue what this would do. And i don't speak russian either.

**Comment by Vladik46** [comment]
If you break a pole sign that will not fall out 323 ID , and 63.

**Pull request closed without merging**
