### PR TITLE
1.4 Update

### PR DESCRIPTION
**Pull request by MisterSheeple**
No protocol changes happened, so nothing else needs changing. I just changed the protocol number

### CODE REVIEW

**Comment by MisterSheeple** [comment]
Why the thumbs down? I updated the protocol number. That's all that needed changing.

**Comment by dktapps** [comment]
This reminds me of all the PRs PM used to get where people would just bump the protocol version and open a PR saying "hey look it works" without actually checking it properly.

**Comment by MisterSheeple** [comment]
I tested it before with the new protocol number and it works flawlessly, and yes, I have checked properly.

**Comment by geNAZt** [comment]
When you did check properly where are the runtime id updates? Where are the new fields from StartGamePacket? Where is the update block change? New PlayState enum values? etc. etc. this is far from "checked" or "complete"

**Comment by NiclasOlofsson** [comment]
Thanks. But as they already commented on, the update is a bit more than just the protocol number. It takes a bit of fiddling and testing to adjust to all the changes. You are welcome to try and figure it out and PR a complete 1.4 implementation if you like.

**Comment by MisterSheeple** [comment]
Just realized I was looking at the wrong apk for changes other than the protocol number. Sorry.

**Pull request closed without merging**
