### PR TITLE
Update MCPE Protocol Documentation.md

### PR DESCRIPTION
**Pull request by Snake1999**
:D

Note:
Dimension - Describes what kind of skylight should be used in destination. 0, main world, 1, nether(red sky).
Target Spawn X Y Z - that should be the position, if no nether gate generates, it generates in this position. 
Unknown - I'm not sure. Maybe gamemode? I test in creative and it's always 0x00.

I'm from Nukkit team. I hope this will help your MiNET developing and make more good minigames :+1:

### CODE REVIEW

**Comment by Pub4Game** [comment]
@Snake1999 Why did you removed it?

**Comment by Snake1999** [comment]
Oops

**Comment by Pub4Game** [comment]
Emm...

**Comment by PEMapModder** [comment]
I'm just interested to know, what if I send 2 in dimension?

**Comment by NiclasOlofsson** [comment]
@Snake1999 Thanks for this info. I'll add the packet to the generation of he packets, so this will auto-update the documentation. I'll keep this open until i do tho.

**Comment by NiclasOlofsson** [comment]
On the PC they also send the difficulty. That could be what that last byte is.

**Pull request closed without merging**
