### PR TITLE
Disallow lighting some blocks on fire

### PR DESCRIPTION
**Pull request by RandomAltThing**

### CODE REVIEW

**Comment by RandomAltThing** [comment]
Block.isSolid() is buggy, so I added this. Also, what is *"Went MIA"*?. I changed it to died.

**Comment by NiclasOlofsson** [comment]
Sorry i want to keep the MIA.

**Comment by RandomAltThing** [comment]
@Niclasaolofsson Why?

**Comment by RandomAltThing** [comment]
@NiclasOlofsson

**Comment by NiclasOlofsson** [comment]
Because it has become a brand thing for MiNET.

**Pull request closed without merging**
