### PR TITLE
Update Sign.cs

### PR DESCRIPTION
**Pull request by Samueljh1**
Added decode method

### CODE REVIEW

**Comment by Samueljh1** [comment]
@NiclasOlofsson call the method in the world provider?
also, for saving this needs to be reversed.

**Comment by LittleBigMC** [comment]
Yay sams back. Thought u died XD

**Comment by GoldishKirby** [comment]
He's back :o

**Comment by Samueljh1** [comment]
Lol

**Comment by LittleBigMC** [comment]
Lol glad ur still doing php. U inspired me and now im one of the top 5 devs
on Imagicalmine :). Thanks sam

**Comment by Samueljh1** [comment]
Wow np and this is c# xD

**Pull request closed without merging**
