### PR TITLE
Replace If/Else with Switch/Case

### PR DESCRIPTION
**Pull request by cFerg**
Generally, after 5 items in a switch/case - the system implements a lookup table ...Meaning faster lookup time

### CODE REVIEW

**Comment by sanderblaadjes** [comment]
Why hasn't this been added yet? :P This speeds up lookup quite a bit. :)

**Comment by NiclasOlofsson** [comment]
Please provide evidence that this is actually more performant. It's usually not that simple when there are numbers involved, and they are non-series (0..n). Usually IF perform better for non-string and numberseries with gaps.

**Comment by ptnalexa** [comment]
@NiclasOlofsson Every C# tutorial will tell you to use switch case rather than if, if your list is greater than 3 or 4(I forgot, actually.). It's your program, though. Develop how you want.

**Comment by cFerg** [comment]
Difference in types:
http://stackoverflow.com/questions/94305/what-is-quicker-switch-on-string-or-elseif-on-type

**Comment by ptnalexa** [comment]
@cFerg You shouldn't worry about "what method is faster?". I'm just saying that switch case is more human readable.

**Comment by cFerg** [comment]
That's true, when you think about it if/else could be say 3.88 nanoseconds ... switch/case could be 2.88 nanoseconds per iteration (just as an example) ... there's 50,000,000 nanoseconds per minecraft tick ... so it's not really 'burdensome' unless you have like 45,000 players or something :P 

Though when I was going through the ItemFactory.cs and was seeing what was missing, what events still needed added etc, it was a whole lot easier to read and mark off things already done/not done.

Not to mention you can actually do multiple ids per statement:

switch(id)
{
    case 0:
    case 1:
        //do this
        break;
    case 2:
    case 3:
       //do this
       break;
}

which would be the same as:

if ((id == 0) || (id == 1))
{
    //do this
}
else if ((id == 2) || (id == 3))
{
    //do this
}

**Comment by ptnalexa** [comment]
@cFerg I totally agree. This should be merged. :)

**Comment by NiclasOlofsson** [comment]
Sorry guys, it's not a voting contest or a debate. You missed the parts in the linked article (and others) that actually states the non obvious that *if* is faster than *switch* in many numerical cases.

But I just asked you to test-run, and you didn't.

**Comment by ptnalexa** [comment]
Are you really debating over "which is faster"? Aren't we going for readability? Switch/case is fast enough, and more human readable.

**Pull request closed without merging**
