### PR TITLE
IMPLEMENT FASTMODE

### PR DESCRIPTION
**Pull request by bettytwin**
HOW IT WORK:

this make minet faster, you turn on and it works!

first , yoyu change value , then turn server ! now 40% faser

### CODE REVIEW

**Comment by NiclasOlofsson** [comment]
It says FALSE? Must reject this.

**Comment by bettytwin** [comment]
should i change to TRUE?

**Comment by NiclasOlofsson** [comment]
Well saying it gets faster and then deliberately setting it to FALSE is .. just false advertisment.

**Comment by bettytwin** [comment]
@NiclasOlofsson can you spealk with less vocab ? .. hard to understand

**Pull request closed without merging**
