### PR TITLE
Enable support for Travis builds

### PR DESCRIPTION
**Pull request by z3ntu**
These will build with Mono instead of the default .NET framework.

### CODE REVIEW

**Comment by NiclasOlofsson** [comment]
I don't want to build it with mono. Is that what this means?

**Comment by z3ntu** [comment]
Shouldn't it be compatible with Mono?

**Comment by NiclasOlofsson** [comment]
tbh, it's not really a goal of mine, no. I'm happy if it works, but I never test for it, and I don't use that ever. Performance on Linux will always be lousy in comparison to Windows.

**Comment by z3ntu** [comment]
Mono works quite well for me. And this configuration with Travis also just builds the .sln file and nothing more.

**Pull request closed without merging**
