### PR TITLE
Implemented Hoe

### PR DESCRIPTION
**Pull request by InusualZ**
I think that I implemented it correctly.

### CODE REVIEW

**Comment by kennyvv** [comment]
Sure, looks good.
However the only problem i can see right now:
Formatting, you changed the formatting... :(
Please fix that, and i guess we can accept it :)

**Comment by InusualZ** [comment]
Witch formatting setting the project have?

**Comment by kennyvv** [comment]
You replaced all tabs with spaces.
Undo that :)

**Comment by NiclasOlofsson** [comment]
I refectored it a bit, but it's in now. Thanks. Guess now we need a lot of work to actually get the logic behind it working too.

**Pull request merged**
